spring.main.allow-bean-definition-overriding: true

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/camunda-sample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver